-- SAFE WITHOUT ERROR
SET SQL_SAFE_UPDATES =0;


-- UPDATE DATA
UPDATE WORKERS SET SALARY = 20000.00 WHERE ID = 5;



-- DELETE SPECIFIC DATA BASED ON THE GIVEN CONDITION
DELETE FROM WORKERS WHERE EMPLOYEE_ID = 6;



-- DROP TABLE REMOVE PERMANANTLY
DROP TABLE WORKERS;
DROP DATABASE WORKERS;




-- TRUNCATE REMOVE DATA ONLY NOT TABLE
TRUNCATE TABLE WORKERS;







-- MODIFY TABLE STRUCTURE ONLY
ALTER TABLE WORKERS
RENAME COLUMN AGE TO PERSON_AGE;

ALTER TABLE WORKERS
RENAME COLUMN NAME TO EMPLOYES_NAME;

ALTER TABLE WORKERS 
RENAME COLUMN ID TO EMPLOYEE_ID;

ALTER TABLE WORKERS 
RENAME COLUMN SALARY TO EMPLOYEE_SALARY;



-- SHOW SPECIFIC DATA BASED ON THE GIVEN CONDITION
SELECT * FROM WORKERS WHERE EMPLOYEE_ID = 3;

