CREATE DATABASE EMPLOY;
USE EMPLOY;
CREATE TABLE EMPLOY(
EMP_ID INT,
EMP_NAME VARCHAR(23),
DEPT_ID INT
);
TRUNCATE TABLE EMPLOY;
INSERT INTO EMPLOY VALUES
(0,'BALAJI AKULA',10),
(1, 'Ravi', 10),
(2, 'Sita', 20),
(3, 'Kiran', 30)
INSERT INTO EMPLOY VALUES(4, 'Anu', 40);
SELECT * FROM EMPLOY;

CREATE TABLE DEPARTMENT(
DEPT_ID INT,
DEPT_NAME VARCHAR(30)
);
INSERT INTO DEPARTMENT VALUES
(10, 'HR'),
(20, 'IT'),
(30, 'Finance'),
(40,'MANAGER');

SELECT * FROM DEPARTMENT;


-- JOINS - JOINS ARE USED TO COMBINE DATA FROM TWO TABLES USING COMMON DATA.
-- 1.INNER JOIN - RETURNS ONLY MATCHING RECORDS FROM BOTH TABLES.

SELECT E.EMP_NAME,D.DEPT_NAME FROM EMPLOY E
INNER JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;














