
-- OPERATORS;

SHOW DATABASES;
CREATE DATABASE STUDENTS;
USE STUDENTS;


CREATE TABLE STUDENTS(
ID INT,
NAME VARCHAR(50),
AGE INT,
GRADE VARCHAR(2),
EMAIL VARCHAR(50)
);

INSERT INTO STUDENTS VALUES
(1,'SAI PASUPULATI',24,'B','sai123@gmail.com'),
(2,'BALAJI AKULA',22,'A','balaji3@gmail.com'),
(3,'NAKKALA JAGADEESH',21,'C','nakkal23@gmail.com'),
(4,'PRANAY KUMAR',22,'B','pranay23@gmail.com');

SELECT * FROM STUDENTS;
-- OPERATORS
-- 1.AND
SELECT * FROM STUDENTS
WHERE AGE > 21 AND GRADE = 'B';

-- 2.OR
SELECT * FROM STUDENTS
WHERE AGE = 21 OR GRADE = 'A';

-- 3.NOT
SELECT * FROM STUDENTS
WHERE NOT GRADE = 'C';

-- 4.IN 
SELECT * FROM STUDENTS
WHERE GRADE IN ('A','B');

-- 5.BETWEEN
SELECT * FROM STUDENTS
WHERE GRADE BETWEEN 'B' AND 'C';

-- 6.LIKE
SELECT * FROM STUDENTS
WHERE NAME LIKE '%N ';

-- 7.IS NULL
SELECT * FROM STUDENTS
WHERE EMAIL IS NULL;

-- 8.IS NOT NULL
SELECT * FROM STUDENTS
WHERE EMAIL IS NOT NULL;

SELECT * FROM STUDENTS;
DESC STUDENTS;

