CREATE DATABASE studentDB;
USE studentDB;

CREATE TABLE studentDB(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
MARKS INT
);

START TRANSACTION;
INSERT INTO studentDB VALUES(1,'BALAJI AKULA',89);
INSERT INTO studentDB VALUES(2,'NAKKALA JAGADEESHWAR REDDY',70);
INSERT INTO studentDB VALUES(3,'PRANAY KUMAR REDDY',89);
COMMIT;
SELECT  FROM studentDB ;

CREATE DATABASE PERSONDB;
CREATE TABLE PERSONDB(
ID INT,
NAME VARCHAR(50),
MARKS INT
);

START transaction;
INSERT INTO PERSONDB VALUES(1,'BALAJI AKULA',89);
INSERT INTO PERSONDB VALUES(2,'NAKKALA JAGADEESHWAR REDDY',70);
INSERT INTO PERSONDB VALUES(3,'PRANAY KUMAR REDDY',89);
ROLLBACK;

SELECT  FROM PERSONDB;

START TRANSACTION;
INSERT INTO PERSONDB VALUES(1,'BALAJI AKULA',89);
SAVEPOINT SP1;
INSERT INTO PERSONDB VALUES(2,'BALAJI AKULA',89);
SAVEPOINT SP2;
INSERT INTO PERSONDB VALUES(3,'BALAJI AKULA',89);
ROLLBACK TO SAVEPOINT SP2;
COMMIT;
SELECT  FROM PERSONDB;

