CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE COLLEGE(
ID INT,
NAME VARCHAR(30),
DEPT_ID int
);
INSERT INTO COLLEGE VALUES
(1,'BALAJI AKULA',10),
(2,'PRANAY',20),
(3,'JAGADESSH',30);

SELECT * FROM COLLEGE;

CREATE TABLE DEPARTMENTS(
DEPT_ID INT,
DEPT_NAME VARCHAR(30)
);

INSERT INTO DEPARTMENTS VALUES
(10,'IT'),
(20,'CSE'),
(40,'ECE');

SELECT * FROM DEPARTMENTS;



SELECT C.ID,C.NAME,D.DEPT_NAME FROM COLLEGE C
INNER JOIN DEPARTMENTS D
ON C.DEPT_ID = D.DEPT_ID;


SELECT C.ID,C.NAME,D.DEPT_NAME FROM COLLEGE C
LEFT JOIN DEPARTMENTS D
ON C.DEPT_ID = D.DEPT_ID;


SELECT C.ID,C.NAME,D.DEPT_NAME FROM COLLEGE C
RIGHT JOIN DEPARTMENTS D
ON C.DEPT_ID = D.DEPT_ID;

SELECT C.ID,C.NAME,D.DEPT_NAME FROM COLLEGE C
LEFT JOIN DEPARTMENTS D
ON C.DEPT_ID = D.DEPT_ID
UNION
SELECT C.ID,C.NAME,D.DEPT_NAME FROM COLLEGE C
RIGHT JOIN DEPARTMENTS D
ON C.DEPT_ID = D.DEPT_ID;


SELECT C.ID,C.NAME,D.DEPT_NAME FROM COLLEGE C
CROSS JOIN DEPARTMENTS D;

ALTER TABLE COLLEGE
ADD MENTOR_ID INT;

SET SQL_SAFE_UPDATES = 0;

UPDATE COLLEGE SET MENTOR_ID = 2 WHERE ID = 1;  -- Top mentor
UPDATE COLLEGE SET MENTOR_ID = 1 WHERE ID = 2;    -- PRANAY's mentor is BALAJI
UPDATE COLLEGE SET MENTOR_ID = 1 WHERE ID = 3;    -- JAGADESSH's mentor is BALAJI


SELECT 
    S.NAME AS Student,
    M.NAME AS Mentor,
    D.DEPT_NAME AS Department
FROM COLLEGE S
LEFT JOIN COLLEGE M
ON S.MENTOR_ID = M.ID
LEFT JOIN DEPARTMENTS D
ON S.DEPT_ID = D.DEPT_ID;

Self Join is a join where a table joins with itself.
